### ISSUE TITLE
Remove `.git` at the end of project name

### ISSUE THREAD

**Issue by jonas-martinez** [shiipou/clone-project-manager#1]
When cloning a project, its name is set to `project-name.git`. It should be set to `project-name`.

**Comment by shiipou** [comment]
Yes that can help to not clone two times the same repository. 

i can also remove trailing `/` at the same times because that cause the script create wrong values for vscode.

I can did that by modifying the current regex.

**Comment by shiipou** [comment]
Fixed with rust rewrite
