### ISSUE TITLE
ci: CI publishes to cargo when no new version 

### ISSUE THREAD

**Issue by jonas-martinez** [shiipou/clone-project-manager#13]
It seems that the CI is trying to publish on cargo even when there is no new version to publish. 
This happened for example when the README was updated with a `docs:` commit.

For more information, refer to : https://github.com/shiipou/clone-project-manager/actions/runs/10856108708/job/30130128337#step:9:87

**Comment by shiipou** [comment]
OK, I'll look at this, thanks for the report

**Comment by shiipou** [comment]
Must be fixed by https://github.com/shiipou/clone-project-manager/commit/e5761fc684e141efd351ce215b888d99841cbe99
